services:
    backend:
        build: ./backend
        ports:
            - "8443:8443"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/nacos_funaab
            - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - FLUTTERWAVE_SECRET=${FLUTTERWAVE_SECRET}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - FRONTEND_DOMAIN_URL=http://frontend:80
            - ALLOWED_CORS_ORIGINS=${ALLOWED_CORS_ORIGINS}
        depends_on:
            - db

    frontend:
        build: ./client
        ports:
            - "80:80"
        environment:
            - VITE_BACKEND_API_BASE_URL=http://backend:8443
        depends_on:
            - backend

    db:
        image: "postgres:latest"
        environment:
            - POSTGRES_DB=nacos_funaab
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
